#include <iostream>
using namespace std;
void nhapmang(int *a,int n){
    for (int i=0;i<n;i++)
    {
        cout<<"a["<<i<<"] = ";
        cin>>*(a+i);
    }
}
void xuatmang(int *a,int n)
{
    for (int i=0;i<n;i++)
    {
        cout<<*(a+i)<<" ";
    }
}
int tansuatxuathien(int *a,int n){
    int max=1;
    for (int i=0;i<n;i++)
    {
        int count =1;
        for (int j=i+1;j<n;j++)
        {
            if(*(a+i) == *(a+j))
            {
                count ++;
            }
        }
        if (count>max)
        {
            max = count;
        }
    }
    return max;
}
int demtansoxuathien(int *a,int n,int index)
{
    int count =1;
    for (int i=index+1;i<n;i++)
        if (*(a+i)==*(a+index))
            count ++;
    return count;
}
void lietke(int *a,int n)
{
    int tansuatmax= tansuatxuathien(a,n);
    if (tansuatmax>1) {
        for (int i = 0; i < n; i++) {
            int tanxuat = demtansoxuathien(a, n, i);
            if (tanxuat == tansuatmax) {
                cout << "\nPhan tu xuat hien nhieu nhat la: " << *(a + i);
            }
        }
    }
    else
        cout << "\nSo lan moi phan tu xuat hien la: 1 ";
    cout<<"\nSo lan xuat hien la: "<<tansuatmax;
}
int main()
{
    cout<<"nhap so phan tu "<<endl;
    int n;
    cin>>n;
    int *a=new int[n];
    nhapmang(a,n);
    xuatmang(a,n);
    lietke(a,n);
    delete a;
}